import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import './theme-config.css';
import NavBar from "./NavBar";
import { Inter } from "next/font/google";
import "@radix-ui/themes/styles.css";
import {Theme, ThemePanel} from '@radix-ui/themes'



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Theme accentColor="lime" radius="small">
        <body className="inter.variable">
          <NavBar />
          <main className="p-5">{children}</main>
        </body>
        {/* <ThemePanel /> */}
      </Theme>
    </html>
  );
}
